Algoritmo "descobrindo area"

Var
 L, C, area, preco, metroQuadrado : real



Inicio
 escreva (" digite a largura do terreno :" )
  leia (L)
 escreva (" digite a comprimento do terreno :")
  leia (C)
 escreva (" digite o valor do m² do terreno :")
  leia (metroQuadrado)

   area <- L * C
 preco <- area * metroQuadrado

escreval (" O terreno tem uma area total de :",area ,"m²s quadrados")
escreval (" O valor do terreno é de R$ :",preco)
 


Fimalgoritmo